{{- $configContent := "" }}
{{- if not .Values.renovate.configEnableHelmTpl }}
  {{- $configContent = required "A valid .Values.renovate.config entry is required if existingConfigFile is not specified!" .Values.renovate.config | nindent 4 }}
{{- else }}
  {{- $configContent = required "A valid .Values.renovate.config entry is required if existingConfigFile is not specified!" (tpl .Values.renovate.config .) | nindent 4 }}
{{- end }}

{{- if not .Values.renovate.existingConfigFile }}
apiVersion: v1
{{- if .Values.renovate.configIsSecret }}
kind: Secret
type: Opaque
{{- else }}
kind: ConfigMap
{{- end }}
metadata:
  name: {{ template "renovate.fullname" . }}-config
  labels:
    {{- include "renovate.labels" . | nindent 4 }}
{{- if .Values.renovate.configIsSecret }}
stringData:
{{- else }}
data:
{{- end }}
{{- if .Values.renovate.configIsJavaScript }}
  config.js: |-
  {{ $configContent }}
{{- else }}
  config.json: |-
  {{ $configContent }}
{{- end }}
{{- end }}
