{{- if .Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "renovate.fullname" . }}-secret
  labels:
    app: {{ template "renovate.name" . }}
    chart: {{ template "renovate.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  {{- range $k, $v := index .Values.secrets }}
  {{ $k }}: {{- $v | b64enc | indent 2 }}
  {{- end }}
  {{- end }}
