name: devcontainer
on:
  push:
    branches:
      - '**'
      - '!main'
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review

jobs:
  devcontainer-test:
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request' || (github.repository_owner != github.event.pull_request.head.repo.owner.login && github.event.pull_request.draft != true)
    steps:
      - name: Checkout
        uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09 # v5.1.0
        with:
          submodules: true

      - name: Build and run dev container task
        uses: devcontainers/ci@513af61f4de4f75d37e4438f184ba4358f0fc1ca # v0.3.1900000450
        with:
          runCmd: ct lint --config .github/ct.yaml --charts charts/renovate
          env: GITHUB_TOKEN
        env:
          GITHUB_TOKEN: ${{ github.token }}
